apiVersion: kaito.sh/v1beta1
kind: Workspace
metadata:
  name: workspace-phi-4-mini
resource:
  preferredNodes:
    - aks-a10pool-13804173-vmss000000
    # - aks-a100pool-30379952-vmss000000
    # - aks-h100pool-10497385-vmss000000
  labelSelector:
    matchLabels:
      apps: guidellm
inference:
  preset:
    name: phi-4-mini-instruct